#!/usr/bin/env bash
# Bash script that prints "Best school" and "hi"

i=1
while (( i <= 10 ))
do
    if (( i == 9 ))
    then
        echo "Best School"
        echo "hi"
        (( i += 1 ))
    else
    echo "Best School"
    fi
    (( i += 1 ))
done
