#!/usr/bin/env bash
# Bash script that prints "Best school" 10 times and on the 9th line it prints "Best School" and "hi" on a new line

i=1
while (( i <= 10 )); do
    if (( i == 9 )); then
        echo "Best School";
        echo "hi";
        continue
    fi 
    echo "Best School";
    (( i += 1 ))
done
